##### config.yml file use to configure applications ###
# Environments: Setup ip sniffing to detect environments
# 
#  Hopefully entirely unnecessary most of the time - 
#  Local ranges 127., 10. and 192. default to development


# environments:
#   development:  172.*
#   production:   86.54.101.70



# == Database configuration ==
development:
 db:
  dbtype: none  
  host: localhost
  database: app_development
  username: root
  password: secret

test:
  db:
    dbtype: mysql
    host: localhost
    database: app_test
    username: root
    password: secret

production: 
  db: 
    dbtype: mysql
    host: localhost
    database: app_production
    username: root
    password: secret

#  == Maintenance downtime == 
#  Use to make the site unavailable to all but one ip
#  Just comment the lines out to operate the site normally. Note that this will need to be your public ip address.
#  Redirect gives an address to redirect all requests to.
#  the ip can be a yaml array or a single ip - both regex 
#maintenance: 
  #ip:       ^127.0.0*
  #redirect: 503.html

